seq="AGACGCGCCCTACCGACCGTGCGCCGGGTGTAATTGGTTATTTTAACTACTTGAACCTCATTGATTGCTAATTTCCGAGTAATGCTGCGGCGATATCGCAAACTACAGACTAGCGGAAAAGAGCCTAGCATGCGTGGATCTAGTCATTAACCATGGGGTGACGGGGGCTGAGGGTACCCACACCCCCCTCATTATGTTAGGAATAATGTTGAATGTGCCCGCGGGCTAACTGTCCAGCATACACGTATGCACGGGTTCATTTACATGTCACGCTACGCATGATCCAAACTAACAGATATACATTACCAGCACACACCCACATCGTTCGTTGGCTCGTCTGGGGACACTCTTGCGTGGTTGAATTTACGCGATCCGAGGTTGCATGAGCGAACTTGAGAAGGGTCGCGCCTGATAAGCCGAAACGTAAACCGAGATGATTTCGTCGGCGCGTCAAGGCACTCTACGGCAAGTGTTCGGACGGTAATAGGCGTAGAAGACTTAGTCCGCACCCGTAGCCGACCACAACCCGAGTTGCCTGGAGGAATGCTAGAATTACGAGGATCAACTGTGCTCCCCGTCAGCCTTTAAAGCGATTTGATTATTGGGGCGGATCCCCGGCTAGGGTCTATTTTGTAGCGTAATATCTGGGCTATGGGTGCTCAACCGGAGCGCGGATATTCCAGCGTGGTTTACCTGTATGGCATAATGAATAAGCATCGCTCCGTATGAAGTACCGCGTAGTATATAGAGAGTGTACACACTCGCATCCTAACATCGCCTGCAGGTTTACAAGCCCTAGCACGAGTGCTGACCTACGCAGGCTACAATCCCCAGACTGTCTGACGGAACTAGACCATACTCGCT"
A=0
C=0
G=0
T=0
for x in seq:
    if x=="A":
        A+=1
    if x=="C":
        C+=1
    if x=="G":
        G+=1
    if x=="T":
        T+=1
print(str(A) + " " + str(C) + " " + str(G) + " " + str(T))